<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\Playlists\" />
    <Folder Include="Components\Pages\Serchs\" />
    <Folder Include="Components\Pages\Friends\" />
    <Folder Include="Components\Pages\Sessions\" />
    <Folder Include="wwwroot\bootstrap\" />
  </ItemGroup>

</Project>
