version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=jb_db;userid=jb_user;password=sleepingondayoff;AllowPublicKeyRetrieval=True;

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sleepingondayoff
      MYSQL_DATABASE: jb_db
      MYSQL_USER: jb_user
      MYSQL_PASSWORD: sleepingondayoff
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
