version: "3.8"

services:
  #MySQL コンテナ
  mysql:
    image: mysql:8.0
    container_name: jambubble
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - jambubble:/var/lib/mysql

  #ASP.NET Core
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    container_name: jambubble_server
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9001
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - JWT__KEY=${JWT__KEY}
      - JWT__ISSUER=${JWT__ISSUER}
      - JWT__AUDIENCE=${JWT__AUDIENCE}
    # ↑ 重要：ここで MySQL への接続文字列を渡す
    # "server=mysql" ← docker-compose 内のサービス名で接続
    # Macの場合、コード内で.envの変数を直接使えない？
    # そのため.env->docker-compose.yml->コンテナ環境変数の順で渡す

volumes:
  jambubble:
