use jambubble_db;

insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (101, 'sniche0', 'skibbel0@bigcartel.com', '$2a$04$frEJYpmvF8X0mK18FqoEOeGVbtXDGtT0g3bBta49mO1vDOzd7lGoa', 3, true, 'http://yellowpages.com/in/quis/justo/maecenas/rhoncus/aliquam/lacus.html', '2025-10-25', 'Soothing tea with honey and ginger, great for relaxation.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (102, 'cbayston1', 'kolivo1@webmd.com', '$2a$04$v9vm8QLqnhCWMuUsgzsgEelVkRz21rR10aBBcUHfWkDW00TkLiLnK', 2, true, 'http://washingtonpost.com/morbi/odio/odio/elementum/eu/interdum.jpg', '2025-09-12', 'Versatile multi-cooker for pressure cooking and slow cooking.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (103, 'zbuyers2', 'nbutton2@discuz.net', '$2a$04$3C5buYfukBvXZcoI8x1oSuBveTd60Fct7tTRWvfpfbKWajpfncine', 1, true, 'https://cdc.gov/ut/ultrices/vel/augue/vestibulum/ante.jpg', '2025-06-18', 'Delicious vegetable dumplings, perfect for steaming or frying.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (104, 'lgonnet3', 'drosenkranc3@wufoo.com', '$2a$04$RnxLOpwyAtNme549nCbXxuiQnS/WHwnJRtD2T7OVFIEhSY9aBTea2', 1, true, 'http://yellowpages.com/rutrum/nulla/nunc/purus/phasellus/in.jsp', '2025-03-27', 'Convenient shower system for camping and outdoor activities.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (105, 'vlaugier4', 'dwainwright4@mail.ru', '$2a$04$OYJqK8YxOh/P6sLKufcMpOQGdypAytZK.UVR15mnd/zxZFSQZsIG2', 3, true, 'https://theguardian.com/aliquet/massa/id/lobortis/convallis/tortor.jpg', '2025-09-21', 'Cute dispenser for bathrooms or kitchens featuring paw prints.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (106, 'rgriffen5', 'cfarnall5@forbes.com', '$2a$04$K81m11x3CGLRTuuykTFHLOVK0IdOC48GSz6RZ6Q1HCgv.EwJRiZ2W', 3, false, 'https://virginia.edu/suscipit/nulla/elit/ac.jpg', '2025-07-11', 'A trendy fanny pack, perfect for hands-free outings.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (107, 'cmeineken6', 'aoverstone6@photobucket.com', '$2a$04$RDQfvTJ1XaIktPasIPE29uhq/EQLFYKhI31dqahkGktIQcw9km7Tm', 2, true, 'https://csmonitor.com/non/ligula.html', '2025-08-11', 'A blend of nuts, seeds, and dried fruits for snacking.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (108, 'tlerohan7', 'tather7@wp.com', '$2a$04$jmApnzq6mGZPmdJDSgM5zuQaiTyH2KHeZ0Le/MBZWyac1wgkdYqwa', 3, true, 'http://desdev.cn/lectus/in.xml', '2025-05-24', 'Comfortable and reusable face masks in different styles.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (109, 'gmidner8', 'jdelaprelle8@sfgate.com', '$2a$04$y7s13aLXH9Casx/WJFs0JOe828FMbT1UZkjgaOMj9WFYRkDiRr9AW', 3, true, 'http://howstuffworks.com/integer/pede/justo/lacinia/eget/tincidunt/eget.js', '2025-10-17', 'Decadent tart made with rich dark chocolate.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (110, 'nfoulgham9', 'beisig9@sbwire.com', '$2a$04$954pGB2yr1uvSil7A3Q9f.U4YMghtXZ1k9dpY4fuTqlNk.ORMSBuq', 1, true, 'http://multiply.com/rhoncus/aliquet/pulvinar.aspx', '2025-05-14', 'A cozy long cardigan designed for layering in any season.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (111, 'mvearncomba', 'npetrollia@constantcontact.com', '$2a$04$TuQbeQdUTlYExMTwOuM2nuhnrFBoI1H7uUHM1l3wHjeMUV3jIf3V.', 1, true, 'https://hatena.ne.jp/convallis/tortor/risus/dapibus/augue/vel/accumsan.json', '2025-07-14', 'Premium potting soil for indoor plants.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (112, 'cdrib', 'cemblowb@newyorker.com', '$2a$04$1VDOZP2W9dqmt2Btx/e0rO/EsJUWggr4vEarsiTgh0A/SN4Q6nZDa', 1, false, 'https://mediafire.com/sapien/placerat/ante/nulla/justo.png', '2025-03-18', 'Heavy-duty bicycle lock for security.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (113, 'klapennac', 'areisenbergc@dagondesign.com', '$2a$04$Hl6Fe6aTvFbPCqmII1y8oeXQqa7UeQx.0SOuSxYoTo8exe1jKAwVu', 3, false, 'http://github.com/dis/parturient/montes.js', '2025-03-27', 'A blend of dried herbs commonly used in Italian cooking.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (114, 'tbrestond', 'emangand@symantec.com', '$2a$04$tj.9cxe8160NocjMx6VcZ.zNaAMJYwJ14qnT8hJbyW/HxhAddYGeW', 1, true, 'http://addthis.com/sed.js', '2025-09-09', 'Seat belt attachment to keep dogs safe during car rides.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (115, 'ojachtyme', 'cnowicke@ehow.com', '$2a$04$/imf/yNpjSKSTS9HpGB1t.VTdYJFyISQ3o/HVkuPROQ1aeZ7Jpr.q', 1, false, 'https://cpanel.net/nibh.aspx', '2025-06-16', 'Frozen pizza loaded with vegetables and cheese.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (116, 'ccrudgingtonf', 'bstoakleyf@timesonline.co.uk', '$2a$04$e.ZYnqYN3mWKjmatmjPCou7kvLh0aUSlzwFPiRkzoceOYOXgRHtle', 2, true, 'https://simplemachines.org/sed.xml', '2025-03-30', 'Salted sunflower seeds perfect for snacking.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (117, 'fmcgarahang', 'jredhouseg@livejournal.com', '$2a$04$eZa//Bw6LtIsqYjTgjOIeuXefPUonn/6RiXuI/xwCRiAl7Jnfv0ju', 1, false, 'http://deviantart.com/vivamus/vel/nulla/eget/eros.aspx', '2025-11-07', 'Freshly sliced cucumbers, great for salads or snacking.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (118, 'ntunneyh', 'kmckevanyh@nature.com', '$2a$04$WGeG89zIDL82Va9XNowCput3ds2wSFM6ZMyHf6b6VR1FhmYekr2WS', 2, false, 'https://yahoo.co.jp/vestibulum/sit/amet/cursus/id/turpis/integer.aspx', '2025-05-29', 'Frozen mix of colorful stir-fry veggies.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (119, 'hgauchi', 'fforsdikei@ftc.gov', '$2a$04$8VmU3bR5.KOfbtmO9JXOy.IfjsMF2btaWlXDx8IUatiaFBC2NIvEG', 2, true, 'https://nydailynews.com/consequat/metus/sapien/ut.js', '2025-02-20', 'Flavorful chicken wings marinated in a sweet teriyaki glaze.');
insert into users (id, name, email, password, gender, is_street_pass, img_url, birthday, message) values (120, 'tcaramusciaj', 'mitzhakj@i2i.jp', '$2a$04$2UQW3Y7t4cSn2duZiwu8HuONJ.X.LfTWxyKlIl5SmavpLQP/pdvTW', 3, false, 'https://fotki.com/in.xml', '2025-02-04', 'Compact air fryer for healthier cooking.');

SELECT * FROM jambubble_db.users;